### ISSUE TITLE
Database-like output format

### ISSUE THREAD

**Issue by Sergiomdf** [Akorostel/HDARead#1]
Hi.
The company were I work needs a new output format, similar to a normalized database table:
```
timestamp1, tag1, ts1_tag1_value
timestamp1, tag2, ts1_tag2_value
timestamp2, tag1, ts2_tag1_value
timestamp3, tag2, ts3_tag2_value
```
While working on this, I notice that in the code there's an unimplemented `LIST` format. If you reserved it for something like we need, I will use it.
If not, I will define a new name, maybe `RECORD` or `ROW`. Which do you think is better?

Is it ok if I send you a pull request of my changes?

Thank you.

**Comment by Akorostel** [comment]
Hi, sorry for the delayed answer. 
LIST format was used for other purposes, but is now deprecated. I think it's better to assign a new name. RECORD is fine.
Pull requests are welcome. Thank you.
